### PR TITLE
Fix APIClient#client_for_resource => raise K8s::Error::UndefinedResource handling

### LINKED ISSUE #16: K8s::APIClient#client_for_resource => NoMethodError: undefined method `kind' for nil:NilClass
Broken error handling for `K8s::APIClient#client_for_resource`.

```
/usr/local/bundle/gems/k8s-client-0.3.1/lib/k8s/client.rb:107:in `client_for_resource'
/usr/local/bundle/gems/k8s-client-0.3.1/lib/k8s/client.rb:113:in `create_resource'
/usr/local/bundle/gems/k8s-client-0.3.1/lib/k8s/stack.rb:86:in `block in apply'
/usr/local/bundle/gems/k8s-client-0.3.1/lib/k8s/stack.rb:74:in `map'
/usr/local/bundle/gems/k8s-client-0.3.1/lib/k8s/stack.rb:74:in `apply'
/app/lib/pharos/addon.rb:205:in `apply_resources'
/app/lib/pharos/addon.rb:171:in `apply_install'
/app/lib/pharos/addon.rb:157:in `apply'
/app/lib/pharos/cluster_manager.rb:126:in `block in apply_addons'
/app/lib/pharos/addon_manager.rb:74:in `block in each'
/app/lib/pharos/addon_manager.rb:86:in `block in with_enabled_addons'
/app/lib/pharos/addon_manager.rb:83:in `each'
/app/lib/pharos/addon_manager.rb:83:in `with_enabled_addons'
/app/lib/pharos/addon_manager.rb:70:in `each'
/app/lib/pharos/cluster_manager.rb:123:in `apply_addons'
/app/lib/pharos/up_command.rb:107:in `configure'
/app/lib/pharos/up_command.rb:44:in `block in execute'
/app/lib/pharos/up_command.rb:43:in `chdir'
/app/lib/pharos/up_command.rb:43:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:63:in `run'
/usr/local/bundle/gems/clamp-1.2.1/lib/clamp/command.rb:132:in `run'
/app/lib/pharos/root_command.rb:16:in `run'
bin/pharos-cluster:12:in `<main>'
```

### PR DESCRIPTION
**Pull request by SpComb**
Fixes #16

The `raise K8s::Error::UndefinedResource` is the only explicitly raised error case in the k8s-client codebase, apart from the API errors raised by the transport, so it makes sense to type that error.

### CODE REVIEW

File: lib/k8s/api_client.rb [hunk 1]
```diff
@@ -67,15 +67,16 @@ def resource(resource_name, namespace: nil)
...
     # @return [K8s::ResourceClient]
     def client_for_resource(resource, namespace: nil)
       unless @api_version == resource.apiVersion
-        raise K8s::Error, "Invalid apiVersion=#{resource.apiVersion} for #{@api_version} client"
+        raise K8s::Error::UndefinedResource, "Invalid apiVersion=#{resource.apiVersion} for #{@api_version} client"
       end
 
       unless api_resource = api_resources.find{ |api_resource| api_resource.kind == resource.kind }
-        raise K8s::Error, "Unknown resource kind=#{api_resource.kind} for #{@api_version}"
+        raise K8s::Error::UndefinedResource, "Unknown resource kind=#{resource.kind} for #{@api_version}"
```
Comment (SpComb) [inline lib/k8s/api_client.rb]: ^ the actual bugfix for #16
